version: '2.1'

services:
  chart-repo-sync:
    image: kubeapps/chart-repo-sync
    environment:
    - MONGO_PASSWORD=password123
    command:
    - /chart-repo-sync
    - --mongo-url=mongodb
    - --mongo-user=root
    - stable
    - https://kubernetes-charts.storage.googleapis.com
    depends_on:
      mongodb:
        condition: service_healthy
  api:
    image: quay.io/deis/go-dev:v1.6.0
    environment:
    - MONGO_PASSWORD=password123
    volumes:
    - .:/go/src/github.com/kubeapps/chartsvc
    working_dir: /go/src/github.com/kubeapps/chartsvc
    command:
    - go
    - run
    - main.go
    - handler.go
    - --mongo-url=mongodb
    - --mongo-user=root
    depends_on:
      mongodb:
        condition: service_healthy
    ports:
    - 8080:8080
  mongodb:
    image: bitnami/mongodb:3
    environment:
      - MONGODB_ROOT_PASSWORD=password123
    healthcheck:
      test:
      - CMD
      - mongo
      - --eval
      - "db.adminCommand('ping')"
