[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.4"

[[constraint]]
  branch = "master"
  name = "github.com/arschles/assert"

[[constraint]]
  branch = "master"
  name = "github.com/kubeapps/common"

[[constraint]]
  branch = "v2"
  name = "gopkg.in/mgo.v2"

[[constraint]]
  branch = "v2"
  name = "gopkg.in/yaml.v2"

[[constraint]]
  name = "k8s.io/helm"
  version = "2.7.2"
[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.1"
